spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test_order
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: order
  security:
    user:
      password: 123456
      name: shenfeng

server:
  port: 9001
  servlet:
    context-path: /order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${server.port}