spring:
  application:
    name: gateway
  security:
    user:
      password: 123456
      name: shenfeng
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path= /user/**
        - id: order
          uri: lb://order
          predicates:
            - Path= /order/**
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true

  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${server.port}